marathon_manager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('admin-django/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('', include('submissions.urls', namespace='submissions')),
]

submissions/urls.py
# Submissions app URLs

from django.urls import path

from submissions import views

app_name = 'submissions'

urlpatterns = [
    # Public views
    path('', views.public.HomeView.as_view(), name='home'),
    path('profile', views.public.ProfileView.as_view(), name='profile'),
    path('submit', views.public.SubmitView.as_view(), name='submit'),
    path('submissions/', views.public.MySubmissionsView.as_view(), name='my-submissions'),
    path('submissions/all', views.public.AllSubmissionsView.as_view(), name='all-submissions'),
    path('submissions/edit/<int:pk>', views.public.EditSubmissionView.as_view(), name='edit-submission'),
    path('submissions/delete/<int:pk>', views.public.DeleteSubmissionView.as_view(), name='delete-submission'),

    # Admin views
    path('admin/settings', views.admin.SettingsView.as_view(), name='admin-settings'),
    path('admin/submissions', views.admin.SubmissionsView.as_view(), name='admin-submissions'),
]

submissions/views/admin.py
"""Admin views for marathon submissions."""

import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import UpdateView, ListView
from social_django.models import UserSocialAuth

from submissions import forms, models
from submissions.views.common import SubmissionViewMixIn

logger = logging.getLogger(__name__)


class AdminViewMixIn(LoginRequiredMixin, PermissionRequiredMixin, SubmissionViewMixIn):
    """Common admin view mix-in to require login with event admin permission and send home if not."""
    permission_required = 'submissions.is_event_admin'

    def handle_no_permission(self):
        logger.error("Unauthorized user {!r} attempting to access admin page".format(self.request.user.username))
        return HttpResponseRedirect(reverse('submissions:home'))


class SettingsView(AdminViewMixIn, UpdateView):
    """Current event settings view."""
    template_name = 'submissions/admin/settings.html'
    form_class = forms.admin.SettingsForm

    def get_object(self, queryset=None):
        """Object we're editing is the current event."""
        return self.event

    def form_valid(self, *args, **kwargs):
        """Add success message after updating."""
        response = super().form_valid(*args, **kwargs)
        messages.add_message(self.request, messages.SUCCESS, _('Event settings updated.'))
        return response

    def get_success_url(self):
        return reverse('submissions:admin-settings')


class SubmissionsView(AdminViewMixIn, ListView):
    template_name = 'submissions/admin/submissions.html'

    def get_queryset(self):
        return models.Submission.objects.filter(event=self.event).select_related(
            'event', 'user', 'user__profile').prefetch_related(
            'categories', Prefetch('user__social_auth',
                                   UserSocialAuth.objects.filter(provider='twitch'), to_attr='twitch_auth'),
            Prefetch('user__availabilities', models.Availability.objects.filter(event=self.event),
                     to_attr='current_event_availabilities')
        )

submissions/views/common.py
"""Common code for submission views."""

import logging

from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views.generic.detail import SingleObjectMixin
from multi_form_view import MultiFormView

from submissions import models

logger = logging.getLogger(__name__)


class FixedMultiFormView(MultiFormView):
    def get_context_data(self, **kwargs):
        """
        Add forms into the context dictionary the proper way.  The regular MultiFormView does not use super() so it
        loses any extra context data from other classes and mix-ins.  To avoid the issue with trying to get the regular
        FormView singular form class, set "form" in kwargs to None so it doesn't try to get it.
        """
        if 'forms' not in kwargs:
            kwargs['forms'] = self.get_forms()
        if 'form' not in kwargs:
            kwargs['form'] = None
        return super(MultiFormView, self).get_context_data(**kwargs)


class SubmissionViewMixIn:
    """Mix-in class for all submission app views to get extra context fields and make sure there's a current event."""
    require_current_event = True
    clear_redirect_to_submit = True

    def _do_extra_data_checks(self):
        """

        Returns:
            django.http.response.HttpResponseRedirect: Redirect response if there's an error, None otherwise.

        """
        # Get next upcoming/active event.
        self.event = models.Event.get_current_event()
        if self.require_current_event and not self.event:
            logger.error("No upcoming active event found")
            return redirect('submissions:home')

        # If user is logged in, make sure they have Twitch auth extra data.
        if self.request.user.is_authenticated:
            twitch_user = self.request.user.social_auth.get(provider='twitch')
            if not twitch_user or not twitch_user.extra_data:
                logger.error("User {!r} does not have Twitch social auth data".format(self.request.user.username))
                logout(self.request)
                return redirect('submissions:home')
            self.request.user.twitch_data = twitch_user.extra_data

            # Cache QuerySet for user submissions and availabilities for the current event.  We use these often enough
            # that it makes sense to cache them on the user object for repeated access.
            self.request.user.current_event_submissions = self.request.user.submissions.filter(
                event=self.event).select_related('event', 'user').prefetch_related('categories')
            self.request.user.current_event_availabilities = self.request.user.availabilities.filter(
                event=self.event).select_related('event', 'user')

        self.extra_context = {
            'event': self.event,
            # Add ranges for max number of games and categories for templates to use in loops.
            'max_games_range': range(self.event.max_games if self.event else 0),
            'max_categories_range': range(self.event.max_categories if self.event else 0),
        }

        # Clear redirect to submit flag for most pages.
        if self.clear_redirect_to_submit:
            self.request.session.pop('redirect_to_submit', False)

    def get(self, request, *args, **kwargs):
        redirect_view = self._do_extra_data_checks()
        if redirect_view:
            return redirect_view
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        redirect_view = self._do_extra_data_checks()
        if redirect_view:
            return redirect_view
        return super().post(request, *args, **kwargs)


class SubmissionViewSingleObjectMixIn(SubmissionViewMixIn, SingleObjectMixin):
    """Mix-in subclass for having a single object view with our extra checks."""

    def _do_extra_data_checks(self):
        redirect_view = super()._do_extra_data_checks()
        if redirect_view:
            return redirect_view

        self.object = self.get_object()

submissions/views/public.py
"""Public views for marathon submissions."""

import datetime
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Prefetch
from django.forms import formset_factory
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.timezone import get_current_timezone
from django.utils.translation import gettext as _
from django.views.generic import TemplateView, ListView, DeleteView
from social_django.models import UserSocialAuth

from submissions import forms, models
from submissions.views.common import SubmissionViewMixIn, FixedMultiFormView, SubmissionViewSingleObjectMixIn

logger = logging.getLogger(__name__)


class HomeView(SubmissionViewMixIn, TemplateView):
    """Home page view."""
    require_current_event = False  # Homepage is okay without a current event.
    template_name = 'submissions/public/home.html'


class ProfileView(LoginRequiredMixin, SubmissionViewMixIn, FixedMultiFormView):
    """User profile and availability."""
    clear_redirect_to_submit = False
    template_name = 'submissions/public/profile.html'
    form_classes = {
        'profile': forms.public.ProfileForm,
        'availability': forms.public.AvailabilityForm,
    }

    def get_success_url(self):
        # If we were redirected here from the submit page, send the user back there.
        if self.request.session.pop('redirect_to_submit', False):
            return reverse('submissions:submit')
        else:
            return reverse('submissions:home')

    def get_form_kwargs(self):
        """Get extra event argument for availability form."""
        form_kwargs = super().get_form_kwargs()
        form_kwargs['availability'].update({
            'event': self.event,
            'user': self.request.user,
        })
        return form_kwargs

    def get_initial(self):
        initial = super().get_initial()

        # Get profile initial fields.
        initial['profile'].update({
            'pronouns': [p.strip() for p in self.request.user.profile.pronouns.split(',')],
        })

        # Get availability initial fields based on current availability intervals.
        for availability in self.request.user.current_event_availabilities:
            hour = availability.start_time.astimezone(get_current_timezone()).replace(minute=0, second=0, microsecond=0)
            while hour < availability.end_time:
                field_name = 'available_{}'.format(hour.strftime('%Y_%m_%d_%H'))
                initial['availability'][field_name] = True
                hour += datetime.timedelta(hours=1)

        return initial

    def forms_valid(self, forms):
        """Update profile and availability records."""
        with transaction.atomic():
            # Update profile pronouns.
            self.request.user.profile.pronouns = ', '.join(forms['profile'].cleaned_data['pronouns'])
            self.request.user.profile.save()

            # Build availability records based on selected hours.  Delete existing records and make fresh ones.
            self.request.user.availabilities.all().delete()
            for availability in forms['availability'].selected_availabilties:
                a = models.Availability(user=self.request.user, event=self.event, start_time=availability[0],
                                        duration=availability[1])
                a.save()

        # Add success message before returning.
        messages.add_message(self.request, messages.SUCCESS, _('Profile updated successfully.'))
        return super().forms_valid(forms)


class MySubmissionsView(LoginRequiredMixin, SubmissionViewMixIn, ListView):
    template_name = 'submissions/public/my_submissions.html'

    def get_queryset(self):
        return self.request.user.current_event_submissions


class AllSubmissionsView(LoginRequiredMixin, SubmissionViewMixIn, ListView):
    template_name = 'submissions/public/all_submissions.html'

    def get_queryset(self):
        return models.Submission.objects.filter(event=self.event).select_related(
            'event', 'user', 'user__profile').prefetch_related(
            'categories', Prefetch('user__social_auth',
                                   UserSocialAuth.objects.filter(provider='twitch'), to_attr='twitch_auth'))


class SubmitView(LoginRequiredMixin, SubmissionViewMixIn, FixedMultiFormView):
    """Submit a run view."""
    template_name = 'submissions/public/submit.html'
    edit_mode = False
    success_message = _('Thank you for your submission!  Check back later to find out which runs have been accepted!')

    def _do_extra_data_checks(self):
        """Override extra data function for this view to get max number of categories for event and set forms."""
        redirect_view = super()._do_extra_data_checks()
        if redirect_view:
            return redirect_view

        # Check if user has profile and availability populated, otherwise redirect them to do this first.
        if not self.request.user.profile.pronouns or not self.request.user.current_event_availabilities.exists():
            logger.info("User {!r} profile not set up, redirecting".format(self.request.user.username))
            self.request.session['redirect_to_submit'] = True
            return redirect('submissions:profile')

        # Initialize category formset factory based on max number of categories per game for the event.
        max_cat = self.event.max_categories
        self.form_classes = {
            'game': forms.public.SubmitGameForm,
            'categories': formset_factory(forms.public.SubmitCategoryForm, extra=max_cat, max_num=max_cat,
                                          validate_max=True, min_num=1, validate_min=True, can_delete=True),
        }

        # Include current number of game submissions for the logged in user and the current submission status.
        self.user_submissions = self.request.user.current_event_submissions.count()
        self.extra_context.update({
            'user_submissions': self.user_submissions,
            'edit_mode': self.edit_mode,
        })

    def get_form_kwargs(self):
        """Get extra user argument for game form."""
        form_kwargs = super().get_form_kwargs()
        args = {
            'event': self.event,
            'user': self.request.user,
        }
        form_kwargs['game'].update(args)
        form_kwargs['categories']['form_kwargs'] = args
        return form_kwargs

    def are_forms_valid(self, *args, **kwargs):
        """Make sure user hasn't reach max number of submissions before doing normal form validation."""
        if self.event.stage not in (self.event.Stages.OPEN, self.event.Stages.LOCKED):
            logger.error("User {} trying to submit form with event {} in stage {}".format(
                self.request.user.username, self.event, self.event.stage))
            return False

        if not self.edit_mode and self.user_submissions >= self.event.max_games:
            logger.error("User {} trying to submit form after reaching max submissions for event {}".format(
                self.request.user.username, self.event))
            return False

        return super().are_forms_valid(*args, **kwargs)

    def get_base_submission(self):
        return models.Submission(user=self.request.user, event=self.event)

    def get_base_categories(self):
        categories = []
        for _ in range(self.event.max_categories):
            categories.append(models.SubmissionCategory())
        return categories

    def forms_valid(self, forms):
        """Create submission records."""
        with transaction.atomic():
            game_data = forms['game'].cleaned_data
            submission = self.get_base_submission()
            submission.game = game_data['game']
            submission.platform = game_data['platform']
            submission.release_year = game_data['release_year']
            submission.twitch_game = game_data['twitch_game']
            submission.description = game_data['description']
            submission.save()

            categories = self.get_base_categories()
            for cat_data, category in zip(forms['categories'].cleaned_data, categories):
                # Remove empty categories that weren't filled in if they existed before.
                if not cat_data.get('category'):
                    if category.pk is not None:
                        category.delete()
                    continue

                category.game = submission
                category.category = cat_data['category']
                category.race = cat_data['race']
                category.estimate = cat_data['estimate']
                category.video = cat_data['video']
                category.save()

        # Add success message before returning.
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return super().forms_valid(forms)

    def get_success_url(self):
        return reverse('submissions:home')


class EditSubmissionView(SubmissionViewSingleObjectMixIn, SubmitView):
    """Edit existing submissions, subclassing from SubmitView to reuse functionality."""
    template_name = 'submissions/public/edit_submission.html'
    context_object_name = 'submission'
    edit_mode = True
    success_message = _('Your submission has been updated successfully.')

    def get_queryset(self):
        return self.request.user.current_event_submissions

    def get_form_kwargs(self):
        """Get extra user argument for game form."""
        form_kwargs = super().get_form_kwargs()
        form_kwargs['game']['submission'] = self.object
        return form_kwargs

    def get_initial(self):
        """Get initial values for game and category forms."""
        initial = super().get_initial()

        initial['game'] = {
            'game': self.object.game,
            'platform': self.object.platform,

submissions/templates/submissions/_layout.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'submissions/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/flatly/bootstrap.min.css" id="bootstrap-link">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static 'submissions/css/main.css' %}">

    <title>
        {% if event %}
            {{ event.name }}
        {% else %}
            Marathon
        {% endif %}
        Submissions
    </title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light">
    <!-- Dropdown -->
    <div class="nav mr-auto dropdown">
        <a href="#" id="navbarDropdownMenuLink" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </a>
        <div class="dropdown-menu">
            {% if user.is_authenticated %}
                <div>
                    <span class="p-2">{{ user.twitch_data.display_name }}</span>
                    <img class="avatar mr-2" src="{{ user.twitch_data.logo }}"
                         title="{{ user.twitch_data.display_name }}"
                         alt="{{ user.twitch_data.display_name }}">
                </div>
                <div class="dropdown-divider"></div>
            {% endif %}

            <a class="dropdown-item" href="{% url 'submissions:home' %}">Home</a>

            {% if user.is_authenticated %}
                <div class="dropdown-divider"></div>
                <div class="dropdown-header">Submissions</div>
                <a class="dropdown-item" href="{% url 'submissions:all-submissions' %}">View All</a>
                <a class="dropdown-item" href="{% url 'submissions:submit' %}">Submit</a>
                <a class="dropdown-item" href="{% url 'submissions:my-submissions' %}">My Submissions</a>
                <div class="dropdown-divider"></div>

                <!-- Admin links -->
                {% if user.is_staff %}
                    <div class="dropdown-header">Admin</div>
                    <a class="dropdown-item" href="{% url 'submissions:admin-submissions' %}">Submissions</a>
                    <a class="dropdown-item" href="{% url 'submissions:admin-settings' %}">Settings</a>
                    <div class="dropdown-divider"></div>
                {% endif %}
            {% endif %}

            <!-- Dark mode switch -->
            <div class="dropdown-item custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="darkSwitch">
                <label class="custom-control-label ml-4 pointer" for="darkSwitch">Dark Mode</label>
            </div>

            <!-- Login/logout links -->
            {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'submissions:profile' %}">Profile &amp; Availability</a>
                <!-- Show link to Django admin for superusers for convenience. -->
                {% if user.is_superuser %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin Site</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="dropdown-item" href="{% url 'social:begin' 'twitch' %}"><i class="fa fa-twitch"></i> Login
                    with Twitch</a>
            {% endif %}
        </div>
    </div>

    <!-- Twitch profile pic and logout button if logged in, otherwise show login button -->
    <div class="nav">
        {% if user.is_authenticated %}
            <span class="py-2">{{ user.twitch_data.display_name }}</span>
            <img class="avatar mt-1 mx-2" src="{{ user.twitch_data.logo }}" title="{{ user.twitch_data.display_name }}"
                 alt="{{ user.twitch_data.display_name }}">
            <a href="{% url 'logout' %}" class="btn btn-twitch">Logout</a>
        {% else %}
            <a href="{% url 'social:begin' 'twitch' %}" class="btn btn-twitch">
                <i class="fa fa-twitch"></i> Login with Twitch</a>
        {% endif %}
    </div>
</nav>

<!-- Main body container.  Show Django messages in bootstrap alerts first, then page content. -->
<div class="{% block container-class %}container{% endblock %} my-2">
    {% bootstrap_messages %}
    {% block content %}{% endblock %}
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<!-- Extra jQuery/Bootstrap plugins. -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/js/bootstrap-multiselect.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

<!-- Dark mode toggle switch JS -->
<script src="{% static 'submissions/js/dark-mode-switch.js' %}"></script>

<!-- Page-specific JS -->
{% block javascript %}{% endblock %}

</body>
</html>

submissions/templates/submissions/_layout_fullscreen.html
{% extends 'submissions/_layout.html' %}

{# Full-screen layout using container-fluid for the main container class to span the entire width. #}
{% block container-class %}container-fluid{% endblock %}